FROM registry.ocp4.example.com:8443/ubi9/nodejs-18-minimal:1-51

ENV PORT=8080
EXPOSE ${PORT}

USER root
RUN chmod -R g=u /var/cache && \
    chgrp -R 0 /var/cache
USER 1001
ADD . $HOME

RUN npm ci --omit=dev && rm -rf .npm
RUN echo "hi"
CMD npm start
