FROM registry.ocp4.example.com:8443/ubi9/nodejs-18-minimal:1-51

ENV PORT=8080
EXPOSE ${PORT}

ADD . $HOME

RUN npm ci --omit=dev && rm -rf .npm
RUN echo "hi"

USER root
RUN  chgrp -R 0 /var/cache && \
     chmod -R g+w /var/cache
USER 1001

CMD npm start
